### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MOKknudsen** [dmauser/DHCPServer-On-Azure#1]
Hi,
can you comment a little bit about this ? What throttling has been enabled ? Number of clients per site ? Is it possible to get the throttling removed by opening support case ?

Update: Sept/2021 - There's also a DHCP throttling feature inside the Azure platform that targets DHCP requests and responses packets. That feature also makes this solution not scalable to process large amount of DHCP requests. For more details, please open a support ticket with the Azure Support team.

**Comment by dmauser** [comment]
It is Azure internal fabric throttling and not exposed to customers. There's no way to change it today. Please open a support ticket with Azure to get more details.

**Comment by dmauser** [comment]
Closing issue. Recommended open a support ticket with Azure team
